# Site settings
title: Emerald | A simple Jekyll blog
description: "A minimal blog template, build with Jekyll."
url: "http://archana163.github.io"

# Build settings
baseurl: /cactus-jekyll-theme/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown


